// List of terms in each category that can be read by the main script
// Easy to add/remove or customize these
var terms = {
    'conservative': [
        "second amendment",
        "conservative",
        "Judeo-Christian values",
        "Jesus",
        "guns",
        "God",
        "patriot",
        "constitution",
        "socialism",
        "communism",
        "troops",
        "Obama",
        "pro-life",
        "cancel culture",
        "free speech",
        "military",
        "conservative censorship",
        "Big Tech",
        "Bezos",
        "Zuckerberg",
        "freedom",
        "SJW",
        "jobs",
        "tax cut",
        "fracking",
        "judges",
        "mainstream media",
        "Fox News",
        "border security",
        "respect for law enforcement",
        "Breitbart",
        "AOC",
        "fake news",
        "stock market",
        "clean coal"
    ],
    'maga': [
        "Make America Great Again",
        "Hillary Clinton",
        "Hillary's emails",
        "Trump 2020",
        "Nancy Pelosi",
        "parler",
        "gab",
        "rigged election",
        "Dominion Voting",
        "Hunter Biden",
        "voter fraud",
        "Russia hoax",
        "impeachment hoax",
        "blue lives matter",
        "border wall",
        "Chuck Schumer",
        "antifa",
        "lock her up",
        "stock market",
        "trade deal",
        "China virus",
        "Chyyyna",
        "kung flu",
        "no collusion",
        "stop the steal",
        "OAN",
        "NewsMax",
        "don't tread on me",
        "come and take it",
        "DNC",
        "democrats",
        "hollywood",
        "treated unfairly",
        "burisma"
    ],
    'tinfoil': [
        "Alex Jones",
        "Infowars",
        "5G",
        "mind control",
        "anti-vax",
        "aliens",
        "Bill Gates",
        "9/11 truth",
        "lockdown",
        "new world order",
        "illuminati",
        "mark of the beast",
        "turning the frogs gay",
        "fluoride",
        "Plandemic",
        "flat earth",
    ],
    'q': [
        "pizzagate",
        "pedophile ring",
        "Epstein didn't kill himself",
        "George Soros",
        "militia",
        "Q drops",
        "deep state",
        "revolution",
        "cabal",
        "where we go one we go all",
        "cannibal",
        "sex trafficking",
        "satan worship",
        "the Storm",
        "the Great Awakening",
        "Trump parade"
    ]
};